#  Copyright 2023 Aix-Marseille Université
# "Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements; and to You under the Apache License, Version 2.0. "

common_parameters = {
    'C_m': 200.0,
    't_ref': 5.0,
    'g_L': 10.0,
    'I_e': 0.0,
    'a': 0.0,
    'b': 0.0,
    'V_th': -50.0,
    'E_ex': 0.0,
    'tau_syn_ex': 5.0,
    'E_in': -80.0,
    'tau_syn_in': 5.0,
    'V_peak': 0.0,
    'N_tot': 10 ** 4,
    'p_connect_ex': 0.05,
    'p_connect_in': 0.05,
    'g': 0.2,
    'Q_e': 1.5,
    'Q_i': 5.0
}

# excitatory
excitatory_param = {
    'C_m': common_parameters['C_m'],
    't_ref': common_parameters['t_ref'],
    'V_reset': -55.0,
    'E_L': -63.0,
    'g_L': common_parameters['g_L'],
    'I_e': common_parameters['I_e'],
    'a': common_parameters['a'],
    'b': common_parameters['b'],
    'Delta_T': 2.0,
    'tau_w': 500.0,
    'V_th': common_parameters['V_th'],
    'E_ex': common_parameters['E_ex'],
    'tau_syn_ex': common_parameters['tau_syn_ex'],
    'E_in': common_parameters['E_in'],
    'tau_syn_in': common_parameters['tau_syn_in'],
    'V_peak': common_parameters['V_peak'],
    'N_tot': common_parameters['N_tot'],
    'p_connect_ex': common_parameters['p_connect_ex'],
    'p_connect_in': common_parameters['p_connect_in'],
    'g': common_parameters['g'],
    'Q_e': common_parameters['Q_e'],
    'Q_i': common_parameters['Q_i'],
}
# inhibitory
inhibitory_param = {
    'C_m': common_parameters['C_m'],
    't_ref': common_parameters['t_ref'],
    'V_reset': -65.0,
    'E_L': -65.,
    'g_L': common_parameters['g_L'],
    'I_e': common_parameters['I_e'],
    'a': common_parameters['a'],
    'b': common_parameters['b'],
    'Delta_T': 0.5,
    'tau_w': 1.0,
    'V_th': common_parameters['V_th'],
    'E_ex': common_parameters['E_ex'],
    'tau_syn_ex': common_parameters['tau_syn_ex'],
    'E_in': common_parameters['E_in'],
    'tau_syn_in': common_parameters['tau_syn_in'],
    'V_peak': common_parameters['V_peak'],
    'N_tot': common_parameters['N_tot'],
    'p_connect_ex': common_parameters['p_connect_ex'],
    'p_connect_in': common_parameters['p_connect_in'],
    'g': common_parameters['g'],
    'Q_e': common_parameters['Q_e'],
    'Q_i': common_parameters['Q_i']
}

params_all = {
    'C_m': common_parameters['C_m'],
    't_ref': common_parameters['t_ref'],
    'V_reset_e': excitatory_param['V_reset'],
    'V_reset_i': inhibitory_param['V_reset'],
    'E_L_e': excitatory_param['E_L'],
    'E_L_i': inhibitory_param['E_L'],
    'g_L': common_parameters['g_L'],
    'I_e': common_parameters['I_e'],
    'a': common_parameters['a'],
    'b': common_parameters['b'],
    'Delta_T_e': excitatory_param['Delta_T'],
    'Delta_T_i': inhibitory_param['Delta_T'],
    'tau_w_e': excitatory_param['tau_w'],
    'tau_w_i': inhibitory_param['tau_w'],
    'V_th': common_parameters['V_th'],
    'E_ex': common_parameters['E_ex'],
    'tau_syn_ex': common_parameters['tau_syn_ex'],
    'E_in': common_parameters['E_in'],
    'tau_syn_in': common_parameters['tau_syn_in'],
    'V_peak': common_parameters['V_peak'],
    'N_tot': common_parameters['N_tot'],
    'p_connect_ex': common_parameters['p_connect_ex'],
    'p_connect_in': common_parameters['p_connect_in'],
    'g': common_parameters['g'],
    'Q_e': common_parameters['Q_e'],
    'Q_i': common_parameters['Q_i']
}
